services:
  webscraper:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./:/context
    depends_on:
      - selenium_scraper

  selenium_scraper:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - app_network

networks:
  app_network: